services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
#    network_mode: host
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - service1
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
#    network_mode: host
    ports:
      - 3000:3000
  service1:
    build: ./service1
    container_name: service1
#    network_mode: host
    ports:
    - 8080:8080
  service2:
    build: ./service2
    container_name: service2
#    network_mode: host
    ports:
      - 8081:8081